# Generated by Django 3.1.4 on 2021-02-17 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_private',
            name='Mode',
        ),
        migrations.RemoveField(
            model_name='post_public',
            name='Mode',
        ),
    ]
